#linux-run.sh LINUX_USER_PASSWORD NGROK_AUTH_TOKEN LINUX_USERNAME LINUX_MACHINE_NAME

#!/bin/bash

# /home/runner/.ngrok2/ngrok.yml

sudo useradd -m $LINUX_USERNAME

sudo adduser $LINUX_USERNAME sudo

echo "$LINUX_USERNAME:$LINUX_USER_PASSWORD" | sudo chpasswd

sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd

sudo nama host $LINUX_MACHINE_NAME

if [[ -z "$NGROK_AUTH_TOKEN" ]]; kemudian

  echo "Silakan set 'NGROK_AUTH_TOKEN'"

  keluar 2

fi

jika [[ -z "$LINUX_USER_PASSWORD" ]]; kemudian

  echo "Silakan set 'LINUX_USER_PASSWORD' untuk pengguna: $USER"

  keluar 3

fi

echo "### Instal ngrok ###"

wget -q https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip

unzip ngrok-stable-linux-386.zip

chmod +x ./ngrok

echo "### Perbarui pengguna: $USER password ###"

echo -e "$LINUX_USER_PASSWORD\n$LINUX_USER_PASSWORD" | sudo passwd "$USER"

echo "### Mulai ngrok proxy untuk 22 port ###"

rm -f .ngrok.log

./ngrok authtoken "$NGROK_AUTH_TOKEN"

./ngrok tcp 22 --log ".ngrok.log" &

tidur 10

HAS_ERRORS=$(grep "perintah gagal" < .ngrok.log)

jika [[ -z "$HAS_ERRORS" ]]; kemudian

  gema ""

  echo "=========================================="

  echo "Untuk menghubungkan: $(grep -o -E "tcp://(.+)" < .ngrok.log | sed "s/tcp:\/\//ssh $USER@/" | sed "s/ :/ -P /")"

  echo "atau sambungkan dengan $(grep -o -E "tcp://(.+)" < .ngrok.log | sed "s/tcp:\/\//ssh (Nama Pengguna Linux Anda)@/" | sed "s/:/ -p /")"

  echo "=========================================="

lain

  gema "$HAS_ERRORS"

  keluar 4

fi
